apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapsontech2
spec:
  selector:
    matchLabels:
      app: rapsontech2
  template:
    metadata:
      labels:
        app: rapsontech2
    spec:
      containers:
        - name: rapsontech2
          image: rapsonwalex/rapsontech2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapsontech2db
spec:
  selector:
    matchLabels:
      app: rapsontech2db
  template:
    metadata:
      labels:
        app: rapsontech2db
    spec:
      containers:
        - name: rapsontech2db
          image: rapsonwalex/rapsontech2db
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapsontech2-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rapsontech2
                port:
                  number: 80
